apiVersion: v1
kind: ReplicationController
metadata:
   name: myjavaapp-rc
spec:
  replicas: 3
  selector: 
     app: myjavaapp
     version: 2.6.2
  template:
     metadata:
       labels:
           app: myjavaapp
           version: 2.6.2
     spec:
        containers:
         - name: myjavaapp-container
           image: nbktechnosys/mahalogin4may22
           ports:
           - containerPort: 8080